<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Orders">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="result">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:byte" name="totalCount"/>
              <xs:element name="order" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:dateTime" name="creationTime"/>
                    <xs:element type="xs:string" name="entityObjectStatusCode"/>
                    <xs:element type="xs:string" name="sellerCode"/>
                    <xs:element type="xs:string" name="buyerCode"/>
                    <xs:element type="xs:byte" name="paymentDiscount"/>
                    <xs:element type="xs:byte" name="discountDays"/>
                    <xs:element type="xs:byte" name="eomDays"/>
                    <xs:element type="xs:string" name="eom"/>
                    <xs:element type="xs:byte" name="netDueDays"/>
                    <xs:element type="xs:string" name="lastRecord"/>
                    <xs:element type="xs:string" name="firstRecord"/>
                    <xs:element type="xs:dateTime" name="enteredDate"/>
                    <xs:element type="xs:short" name="creatorUserId"/>
                    <xs:element type="xs:string" name="orderConfirmationFile"/>
                    <xs:element type="xs:string" name="sharedWithUsers"/>
                    <xs:element type="xs:string" name="isOwnedByMe"/>
                    <xs:element type="xs:string" name="creatorTenantName"/>
                    <xs:element type="xs:string" name="isOrderInformationValid"/>
                    <xs:element type="xs:string" name="isBuyerContactInformationValid"/>
                    <xs:element type="xs:string" name="isSellerContactInformationValid"/>
                    <xs:element type="xs:string" name="isSalesRepInformationValid"/>
                    <xs:element type="xs:string" name="isShippingInformationValid"/>
                    <xs:element type="xs:string" name="isBillingInformationValid"/>
                    <xs:element type="xs:string" name="entityCategoriesNames"/>
                    <xs:element type="xs:string" name="entityClassificationsNames"/>
                    <xs:element type="xs:string" name="enteredByUserRole"/>
                    <xs:element type="xs:string" name="buyerCompanySSIN"/>
                    <xs:element type="xs:string" name="buyerCompanyName"/>
                    <xs:element type="xs:string" name="sellerId"/>
                    <xs:element type="xs:string" name="sellerCompanyName"/>
                    <xs:element type="xs:string" name="buyerContactEMailAddress"/>
                    <xs:element type="xs:byte" name="languageId"/>
                    <xs:element type="xs:string" name="languageCode"/>
                    <xs:element type="xs:short" name="currencyId"/>
                    <xs:element type="xs:string" name="currencyCode"/>
                    <xs:element type="xs:string" name="sellerContactEMailAddress"/>
                    <xs:element type="xs:string" name="buyerContactPhoneNumber"/>
                    <xs:element type="xs:string" name="sellerContactPhoneNumber"/>
                    <xs:element type="xs:string" name="buyerContactName"/>
                    <xs:element type="xs:string" name="sellerContactName"/>
                    <xs:element type="xs:string" name="priceLevel"/>
                    <xs:element type="xs:string" name="buyerContactSSIN"/>
                    <xs:element type="xs:string" name="buyerBranchSSIN"/>
                    <xs:element type="xs:string" name="buyerBranchName"/>
                    <xs:element type="xs:string" name="sellerBranchSSIN"/>
                    <xs:element type="xs:string" name="sellerBranchName"/>
                    <xs:element type="xs:string" name="sellerContactSSIN"/>
                    <xs:element type="xs:byte" name="transactionType"/>
                    <xs:element type="xs:string" name="entityStatusCode"/>
                    <xs:element type="xs:dateTime" name="completeDate"/>
                    <xs:element type="xs:string" name="sellerCompanySSIN"/>
                    <xs:element type="xs:dateTime" name="startDate"/>
                    <xs:element type="xs:dateTime" name="availableDate"/>
                    <xs:element type="xs:int" name="shipViaId"/>
                    <xs:element type="xs:string" name="shipViaCode"/>
                    <xs:element type="xs:string" name="shipViaName"/>
                    <xs:element type="xs:int" name="paymentTermsId"/>					
					<xs:element type="xs:string" name="paymentTermsName"/>					
                    <xs:element type="xs:string" name="paymentTermsCode"/>
                    <xs:element type="xs:string" name="buyerDepartment"/>
                    <xs:element name="appTransactionsDetails" maxOccurs="unbounded" minOccurs="0">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element type="xs:byte" name="transactionCode"/>
                          <xs:element type="xs:byte" name="lineNo"/>
                          <xs:element type="xs:byte" name="quantity"/>
                          <xs:element type="xs:float" name="grossPrice"/>
                          <xs:element type="xs:float" name="netPrice"/>
                          <xs:element type="xs:byte" name="discount"/>
                          <xs:element type="xs:float" name="amount"/>
                          <xs:element type="xs:byte" name="itemId"/>
                          <xs:element type="xs:string" name="itemCode"/>
                          <xs:element type="xs:string" name="itemDescription"/>
                          <xs:element type="xs:string" name="note"/>
                          <xs:element type="xs:string" name="ssin"/>
                          <xs:element type="xs:string" name="manufacturerCode"/>
                          <xs:element type="xs:int" name="id"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element name="appTransactionContacts" maxOccurs="unbounded" minOccurs="0">
                      <xs:complexType>
                        <xs:sequence>
                          <xs:element type="xs:int" name="transactionId"/>
                          <xs:element type="xs:string" name="contactSSIN"/>
                          <xs:element type="xs:string" name="contactName"/>
                          <xs:element type="xs:string" name="companyName"/>
                          <xs:element type="xs:string" name="contactEmail"/>
                          <xs:element type="xs:string" name="contactPhoneNumber"/>
                          <xs:element type="xs:byte" name="contactRole"/>
                          <xs:element type="xs:string" name="branchName"/>
                          <xs:element type="xs:string" name="companySSIN"/>
                          <xs:element type="xs:string" name="branchSSIN"/>
                          <xs:element type="xs:string" name="contactPhoneTypeName"/>
                          <xs:element type="xs:string" name="contactPhoneTypeId"/>
                          <xs:element type="xs:string" name="contactAddressId"/>
                          <xs:element type="xs:string" name="contactAddressCode"/>
                          <xs:element name="contactAddressDetail">
                            <xs:complexType mixed="true">
                              <xs:sequence>
                                <xs:element type="xs:string" name="contactEmail" minOccurs="0"/>
                                <xs:element type="xs:string" name="contactPhone" minOccurs="0"/>
                                <xs:element type="xs:string" name="code" minOccurs="0"/>
                                <xs:element type="xs:short" name="tenantId" minOccurs="0"/>
                                <xs:element type="xs:int" name="accountId" minOccurs="0"/>
                                <xs:element type="xs:string" name="name" minOccurs="0"/>
                                <xs:element type="xs:string" name="addressLine1" minOccurs="0"/>
                                <xs:element type="xs:string" name="addressLine2" minOccurs="0"/>
                                <xs:element type="xs:string" name="city" minOccurs="0"/>
                                <xs:element type="xs:string" name="state" minOccurs="0"/>
                                <xs:element type="xs:string" name="postalCode" minOccurs="0"/>
                                <xs:element type="xs:short" name="countryId" minOccurs="0"/>
                                <xs:element type="xs:string" name="countryCode" minOccurs="0"/>
                                <xs:element type="xs:string" name="countryIdName" minOccurs="0"/>
                                <xs:element type="xs:string" name="useDTOTenant" minOccurs="0"/>
                                <xs:element type="xs:int" name="id" minOccurs="0"/>
                              </xs:sequence>
                            </xs:complexType>
                          </xs:element>
                          <xs:element type="xs:string" name="selectedCompany"/>
                          <xs:element type="xs:string" name="selectedContact"/>
                          <xs:element type="xs:string" name="selectedBranch"/>
                          <xs:element type="xs:string" name="selectedPhoneType"/>
                          <xs:element type="xs:string" name="selectContactPhoneNumber"/>
                          <xs:element type="xs:string" name="selectedContactEmail"/>
                          <xs:element type="xs:string" name="contactAddressName"/>
                          <xs:element type="xs:string" name="contactAddressLine1"/>
                          <xs:element type="xs:string" name="contactAddressLine2"/>
                          <xs:element type="xs:string" name="contactAddressCity"/>
                          <xs:element type="xs:string" name="contactAddressState"/>
                          <xs:element type="xs:string" name="contactAddressPostalCode"/>
                          <xs:element type="xs:short" name="contactAddressCountryId"/>
                          <xs:element type="xs:string" name="contactAddressCountryCode"/>
                          <xs:element type="xs:short" name="id"/>
                        </xs:sequence>
                      </xs:complexType>
                    </xs:element>
                    <xs:element type="xs:string" name="buyerStore"/>
                    <xs:element type="xs:byte" name="totalQuantity"/>
                    <xs:element type="xs:float" name="totalAmount"/>
                    <xs:element type="xs:string" name="lFromPlaceOrder"/>
                    <xs:element type="xs:float" name="currencyExchangeRate"/>
                    <xs:element type="xs:string" name="reference"/>
                    <xs:element type="xs:short" name="tenantId"/>
                    <xs:element type="xs:string" name="attachmentSourceTenantId"/>
                    <xs:element type="xs:string" name="name"/>
                    <xs:element type="xs:string" name="code"/>
                    <xs:element type="xs:string" name="notes"/>
                    <xs:element type="xs:string" name="isHostRecord"/>
                    <xs:element type="xs:string" name="addFromAttachments"/>
                    <xs:element type="xs:string" name="relatedEntityId"/>
                    <xs:element type="xs:short" name="entityObjectTypeId"/>
                    <xs:element type="xs:string" name="entityObjectTypeCode"/>
                    <xs:element type="xs:byte" name="entityObjectStatusId"/>
                    <xs:element type="xs:byte" name="objectId"/>
                    <xs:element type="xs:byte" name="appEntityTypes"/>
                    <xs:element type="xs:string" name="ssin"/>
                    <xs:element type="xs:short" name="tenantOwner"/>
                    <xs:element type="xs:int" name="id"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element type="xs:string" name="targetUrl"/>
        <xs:element type="xs:string" name="success"/>
        <xs:element type="xs:string" name="error"/>
        <xs:element type="xs:string" name="unAuthorizedRequest"/>
        <xs:element type="xs:string" name="abp"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>