USE [????]
GO

/****** Object:  Table [dbo].[SYCEDILOG]    Script Date: 01/23/2012 15:59:04 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[SYCEDILOG](
	[CCLIENTID] [varchar](5) NULL,
	[ROWGUIDEID] [uniqueidentifier] NOT NULL,
	[USER_ID] [varchar](20) NOT NULL,
	[EDI_TRANSACTION_TYPE] [varchar](3) NULL,
	[PARTNER_CODE] [varchar](6) NULL,
	[VERSION] [varchar](12) NULL,
	[MAPSET] [varchar](3) NULL,
	[LOOP_ID] [varchar](3) NULL,
	[SEGMENT_ID] [varchar](8) NULL,
	[USAGE] [varchar](1) NULL,
	[NEW_USAGE] [varchar](1) NULL,
	[FIELD_NAME] [varchar](20) NULL,
	[NEW_FIELD_NAME] [varchar](20) NULL,
	[FIELD_CONDITION] [varchar](120) NULL,
	[NEW_FIELD_CONDITION] [varchar](120) NULL,
	[FIELD_VALUE] [varchar](120) NULL,
	[NEW_FIELD_VALUE] [varchar](120) NULL,
	[TYPE] [varchar](10) NULL,
	[FIELD_ORDER] [numeric](2, 0) NULL,
	[ACTION_FLAG] [bit] NULL,
	[REPORT_NAME_BEFORE] [varchar](12) NULL,
	[LABEL_TYPE] [char](6) NULL,
	[REPORT_NAME_AFTER] [varchar](120) NULL,
	[SESSION_DATE] [datetime] NOT NULL,
	[SESSION_ID] [varchar](14) NOT NULL,
 CONSTRAINT [PK_SYCEDILOG] PRIMARY KEY CLUSTERED 
(
	[ROWGUIDEID] ASC,
	[USER_ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[SYCEDILOG] ADD  CONSTRAINT [DF_SYCEDILOG_ROWGUIDEID]  DEFAULT (newid()) FOR [ROWGUIDEID]
GO


